# Generated by Django 3.0.6 on 2020-05-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='egg/color/')),
            ],
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_orders', to='pages.Color'),
        ),
    ]
