# Generated by Django 3.0.6 on 2020-05-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_uniquefeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniquefeature',
            old_name='feature',
            new_name='description',
        ),
    ]
